# vim:ft=kitty
## name: Default Dark (base16)
## author: chriskempson, kitty Theme by EvilsSouls
## license: MIT
## blurb: A theme based on the default dark (base16) theme found at https://github.com/chriskempson/base16-default-schemes

#: The basic colors

foreground                      #d8d8d8
background                      #181818
selection_foreground            #181818
selection_background            #d8d8d8


#: Cursor colors

cursor                          #d8d8d8
cursor_text_color               #181818
cursor_trail_color              none


#: URL underline color when hovering with mouse

url_color                       #7cafc2


#: kitty window border colors and terminal bell colors

active_border_color             #a1b56c
inactive_border_color           #b8b8b8
bell_border_color               #ab4642
# visual_bell_color               none


#: OS Window titlebar colors

# wayland_titlebar_color          system
# macos_titlebar_color            system


#: Tab bar colors

active_tab_foreground           #181818
active_tab_background           #a1b56c
inactive_tab_foreground         #4E5932
inactive_tab_background         #181818
# tab_bar_background                none
# tab_bar_margin_color              none


#: Colors for marks (marked text in the terminal)

# mark1_foreground black
# mark1_background #98d3cb
# mark2_foreground black
# mark2_background #f2dcd3
# mark3_foreground black
# mark3_background #f274bc


#: The basic 16 colors

#: black
color0 #181818
color8 #585858

#: red
color1 #ab4642
color9 #c73e37

#: green
color2  #a1b56c
color10 #8cce5c

#: yellow
color3  #f7ca88
color11 #fadd72


#: blue
color4  #7cafc2
color12 #488ddb


#: magenta
color5  #ba8baf
color13 #d376ca


#: cyan
color6  #86c1b9
color14 #75d5d0


#: white
color7  #d8d8d8
color15 #f8f8f8


#: You can set the remaining 240 colors as color16 to color255.
