config_version = 2

[shell]
polkit_agent = true
settings_window_translucent = true
screen_time_enabled = true
clipboard_image_action_command = "satty -f -"

[shell.animation]
speed = 1.25

[shell.greeter_sync]
auto_sync = false

[audio]
enable_sounds = true

[keybinds]
up = [ "Up", "Ctrl+k", "Ctrl-p" ]
down = [ "Down", "Ctrl+j", "Ctrl-n" ]
left = [ "Left", "Ctrl+h" ]
right = [ "Right", "Ctrl+l" ]

[dock]
enabled = false

[nightlight]
enabled = true
